{{- $secretName := .Values.typesense.apiKeySecret }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "jikan-rest.labels" . | nindent 4 }}
type: Opaque
data:
  typesense-apikey: {{ if $existing }}{{ index $existing.data "typesense-apikey" }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
